backend:
  name: git-gateway
  branch: main # Change this to whatever your master is

publish_mode: editorial_workflow

media_folder: "public/uploads" # Media files will be stored here in public/Uploads you'll have to create this
public_folder: "/uploads" # this is the post deployment folder for images